In [1]:
#Importing libraries
import math as m
m.sqrt(10)

3.1622776601683795

In [2]:
import numpy as np

In [3]:
l = [1,2,"3"]
#if one value is a string---> complete convert to string
np.array(l)


array(['1', '2', '3'], dtype='<U21')

In [4]:
print(np.zeros(10))
a = np.ones(19)
print(a)
a.dtype #by default it is float

#make it int
b = np.ones(10, int)
b.dtype

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


dtype('int64')

In [5]:
#2D numpy arrays
l = np.zeros((2,3))
l

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
print(l[0][1])

#slicing 
print(a[2:4])

l.shape

0.0
[1. 1.]


(2, 3)

In [7]:
a = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
print(a[0])
print(a[:,0])  #all the elements
print(a[0:2,0]) 

[1 2 3]
[1 4 1 4]
[1 4]


In [8]:
#Numpy Operations

a = np.array([1,2,3])
b = np.array([5,6,7])

print(a + 2)
print(a + b)
print(a * 2)
print(a * b)
print(a ** 2)
print(a ** b)

[3 4 5]
[ 6  8 10]
[2 4 6]
[ 5 12 21]
[1 4 9]
[   1   64 2187]


In [9]:
print(a.mean())
a.sum()

2.0


6

In [10]:
# matrix multplication

a1 = np.array([[1,2],[3,4]])
a2 = np.array([[10,20],[30,40]])

a1.dot(a2)

array([[ 70, 100],
       [150, 220]])